apiVersion: batch/v1beta1
kind: CronJob
metadata:
 name: myapp
spec:
 schedule: "*/1 * * * *"
 jobTemplate:
  spec:
    completions: 3
    parallelism: 3
    template:
      spec:
       containers:
        - name: myapp
	      image: kodekloud/random
       restartPolicy: Never