apiVersion: batch/v1
kind: Job
metadata:
 name: myapp
spec:
 completions: 3
 parallelism: 3
 template:
  spec:
   containers:
    - name: myapp
	  image: kodekloud/random
   restartPolicy: Never