apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multipodnew
  name: multipodnew
spec:
  containers:
  - command:
    - sleep
    - "3600"
    image: busybox
    name: c1
    resources: {}
  - image: busybox
    name: c2
  - image: busybox
    name: c3  
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
