apiVersion: v1
kind: Pod
metadata:
  name: web-deployment
  labels:
    app: myapp
spec:
  containers:
  - name: nginx
    image: raghuram04/myproject:v1
    imagePullPolicy: Always
    ports:
    - containerPort: 8083      
  imagePullSecrets:
  - name: my-secret
  
## kubectl create secret docker-registry my-secret --docker-server=DOCKER_REGISTRY_SERVER --docker-username=DOCKER_USER --docker-password=DOCKER_PASSWORD --docker-email=DOCKER_EMAIL