apiVersion: v1
kind: Pod
metadata: 
  name: myapp
spec: 
  containers: 
    -       
      image: nginx      
      livenessProbe: 
        tcpSocket: 
          port: 3306
      name: myapp      
      readinessProbe: 
        httpGet: 
          path: /test
          port: 8080
        failureThreshold: 1
        initialDelaySeconds: 80
        periodSeconds: 10