apiVersion: v1
kind: Pod
metadata:
 name: mypod
spec:
 containers:
  - name: myapp
    image: nginx
 affinity:
  nodeAffinity:
   requiredDuringSchedulingIgnoredDuringExecution:
    nodeSelectorTerms:
	 - matchExpressions:
	    - key: node-role.kubernetes.io/master
		  operator: Exists                                       ## Create the pod in master                 
    