apiVersion: v1
kind: Pod
metadata: 
  name: webapp1
spec: 
  containers: 
    - 
      envFrom:
        - 
          secretRef: 
            name: db-secret
      image: nginx
      name: mywebapp