apiVersion: v1
kind: Pod
metadata: 
  labels: 
    app: myapp
    type: sampleapp
  name: myapp-pod
spec:   
  containers: 
    - image: nginx
      name: nginx-containers
   serviceaccount: myaccount
	  